#!/bin/bash
# Turtle Dashboard Generator
# Writes a status dashboard to magic-bridge/shared/dashboard.md
# Runs hourly via crontab

BRIDGE=~/magic-bridge
DASHBOARD="$BRIDGE/shared/dashboard.md"
SHELL_DIR=~/turtle-shell
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
LOCAL_TIME=$(date +"%Y-%m-%d %H:%M %Z")

mkdir -p "$BRIDGE/shared"

# Collect health data
UPTIME=$(uptime | sed 's/.*up /up /' | sed 's/,.*//')
DISK_USED=$(df -h / | tail -1 | awk '{print $3}')
DISK_TOTAL=$(df -h / | tail -1 | awk '{print $2}')
DISK_PCT=$(df -h / | tail -1 | awk '{print $5}')

# Service status
DISCORD_STATUS="DOWN"
pgrep -f discord_bot.py > /dev/null && DISCORD_STATUS="RUNNING"
OLLAMA_STATUS="DOWN"
curl -s http://localhost:11434/api/tags > /dev/null 2>&1 && OLLAMA_STATUS="RUNNING"
BRIDGE_CRON="INACTIVE"
crontab -l 2>/dev/null | grep -q bridge-sync && BRIDGE_CRON="ACTIVE"
AGENT_STATUS="IDLE"
pgrep -f agent.py > /dev/null && AGENT_STATUS="RUNNING SPRINT"

# Model info
MODEL=$(curl -s http://localhost:11434/api/tags 2>/dev/null | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d["models"][0]["name"] if d.get("models") else "none")' 2>/dev/null || echo "unknown")

# Pending commands
PENDING=$(ls "$BRIDGE/commands/"*.yaml 2>/dev/null | wc -l | tr -d ' ')
PENDING_LIST=""
if [ "$PENDING" -gt 0 ]; then
    PENDING_LIST=$(ls "$BRIDGE/commands/"*.yaml 2>/dev/null | while read f; do echo "- $(basename $f)"; done)
fi

# Recent signals
RECENT_SIGNALS=$(ls -t "$BRIDGE/signals/"*.yaml 2>/dev/null | head -5 | while read f; do
    SUMMARY=$(grep 'summary:' "$f" 2>/dev/null | head -1 | sed 's/summary: *//' | tr -d '"')
    echo "- $(basename $f .yaml): $SUMMARY"
done)

# Proposals
PROPOSALS=$(ls ~/turtle-practice/proposals/ 2>/dev/null | while read f; do echo "- $f"; done)

# Last bridge sync
LAST_SYNC=$(tail -1 ~/nanoclaw/logs/bridge-sync.log 2>/dev/null || echo "unknown")

# Sprint log (last 5 lines)
SPRINT_LOG=""
LATEST_LOG=$(ls -t $SHELL_DIR/logs/sprint_*.log 2>/dev/null | head -1)
if [ -n "$LATEST_LOG" ]; then
    SPRINT_LOG=$(tail -5 "$LATEST_LOG" 2>/dev/null)
fi

# Write dashboard
cat > "$DASHBOARD" << EOF
# Turtle Dashboard
> Updated: $LOCAL_TIME ($TIMESTAMP)

---

## Health

| Component | Status |
|-----------|--------|
| Uptime | $UPTIME |
| Disk | $DISK_USED / $DISK_TOTAL ($DISK_PCT) |
| Discord Bot | $DISCORD_STATUS |
| Ollama | $OLLAMA_STATUS ($MODEL) |
| Bridge Sync | $BRIDGE_CRON |
| Agent | $AGENT_STATUS |

## Pending Commands ($PENDING)

$PENDING_LIST

## Recent Signals

$RECENT_SIGNALS

## Active Proposals

$PROPOSALS

## Last Bridge Sync

$LAST_SYNC

## Latest Sprint Activity

$SPRINT_LOG

---

*Auto-generated by dashboard.sh. Read from magic-bridge/shared/dashboard.md.*
EOF

echo "[$TIMESTAMP] Dashboard updated" >> $SHELL_DIR/logs/dashboard.log
