"""`docs/quality-measures.md` must keep reporting what is actually measured.

The document was created to answer "is this getting better or worse", and its
structural numbers are generated by `scripts/quality_baseline.py`. The failure
this guards is the one that produced the document: a report and its generator
drifting apart, so the report keeps reading as current while measuring something
narrower, wider, or gone.

Deliberately *not* guarded: the values in the series. Those are dated historical
facts and must not be rewritten — a test asserting today's numbers would fail on
every commit and be deleted within a week, which is worse than no test. What is
guarded is the correspondence: every metric the script emits for the series has a
column, every column is a metric the script emits, and every hand-kept ledger row
is complete enough to be usable.

**Added 2026-08-15, when the operator adopted these as his measure.** Correspondence
was guarded; *currency* was not. The last row could be months old while the codebase
doubled, and every test here stayed green — the document would keep reading as a live
series while measuring a program that no longer exists. That is the same shape as the
acceptance catalogue drifting 41 commits behind, and the fix has to be the same kind:
the document asks its reader to remember to append a row, and remembering is not a
mechanism.

The check is proportional rather than time-based. A calendar deadline fails on a quiet
week and gets deleted; a threshold on size only fires when there is something new to
measure, and appending the row the script already prints resolves it.
"""

from __future__ import annotations

import re
import sys
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))

import quality_baseline  # noqa: E402

DOC = REPO / "docs" / "quality-measures.md"

# Column header → metric key in the script. The document is written for a reader,
# so its headers are prose; this map is the join, and it is the thing that has to
# stay honest.
COLUMN_TO_METRIC = {
    "date": "date",
    "root modules": "root_modules",
    "packages": "packages",
    "modules ≥1000 lines": "modules_over_1000_lines",
    "prod loc": "production_loc",
    "test loc": "test_loc",
    "test:prod": "test_to_production_ratio",
    "tests": "tests_collected",
    "importing transport": "modules_importing_transport",
    "boundary exemptions": "transport_boundary_exemptions",
    "runtime lines unused": "runtime_lines_unused_by_production",
}


def _tables(text: str) -> list[list[list[str]]]:
    """Every markdown table, as a list of cell-rows."""
    tables: list[list[list[str]]] = []
    current: list[list[str]] = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("|") and stripped.endswith("|"):
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            if all(set(c) <= set("-: ") for c in cells):
                continue  # separator row
            current.append(cells)
            continue
        if current:
            tables.append(current)
            current = []
    if current:
        tables.append(current)
    return tables


def _metric_for(header: str) -> str | None:
    """Headers are written for a reader; the join must not care about case."""
    return COLUMN_TO_METRIC.get(header.strip().lower())


def _table_with_header(text: str, first_cell: str) -> list[list[str]]:
    for table in _tables(text):
        if table and table[0] and table[0][0].lower() == first_cell.lower():
            return table
    raise AssertionError(f"no table found whose first column is {first_cell!r}")


class SeriesTableTests(unittest.TestCase):
    def setUp(self) -> None:
        self.text = DOC.read_text(encoding="utf-8")
        self.table = _table_with_header(self.text, "date")

    def test_every_series_column_is_a_metric_the_script_emits(self) -> None:
        headers = self.table[0]
        unknown = [h for h in headers if _metric_for(h) is None]
        self.assertEqual(
            unknown, [], f"columns with no metric behind them: {unknown}"
        )
        missing = [
            _metric_for(h) for h in headers if _metric_for(h) not in quality_baseline.ROW_FIELDS
        ]
        self.assertEqual(
            missing, [], f"columns whose metric the script no longer emits: {missing}"
        )

    def test_every_metric_the_script_emits_has_a_column(self) -> None:
        """The direction that actually rots: a metric added and never reported."""
        headers = self.table[0]
        reported = {_metric_for(h) for h in headers}
        unreported = [f for f in quality_baseline.ROW_FIELDS if f not in reported]
        self.assertEqual(
            unreported,
            [],
            "the script measures these and the document does not show them — "
            f"add a column or drop them from ROW_FIELDS: {unreported}",
        )

    def test_the_column_order_matches_the_row_the_script_prints(self) -> None:
        """`--row` output is meant to be pasted straight in."""
        headers = self.table[0]
        self.assertEqual(
            [_metric_for(h) for h in headers],
            list(quality_baseline.ROW_FIELDS),
            "`--row` prints fields in ROW_FIELDS order; a pasted row would land "
            "under the wrong headings",
        )

    def test_the_series_has_at_least_one_measurement(self) -> None:
        self.assertGreater(len(self.table), 1, "a series with no rows is a promise")

    def test_every_series_row_is_complete(self) -> None:
        headers = self.table[0]
        for row in self.table[1:]:
            with self.subTest(row=row[0] if row else "?"):
                self.assertEqual(
                    len(row), len(headers), "row does not line up with the headers"
                )
                self.assertRegex(row[0], r"^\d{4}-\d{2}-\d{2}$", "first cell is the date")


class DetectionLedgerTests(unittest.TestCase):
    """The hand-kept half. Cannot be generated; can still be checked for shape."""

    def setUp(self) -> None:
        self.text = DOC.read_text(encoding="utf-8")
        self.table = _table_with_header(self.text, "found")

    def test_the_ledger_has_the_columns_the_measures_need(self) -> None:
        self.assertEqual(
            self.table[0], ["found", "defect", "introduced", "live for", "class"]
        )

    def test_every_entry_names_a_class(self) -> None:
        """Measure 2 is recurrence, and recurrence is unmeasurable without a class."""
        for row in self.table[1:]:
            with self.subTest(defect=row[1][:40]):
                self.assertTrue(row[4].strip(), "no class named — recurrence cannot be seen")
                self.assertTrue(row[3].strip(), "no interval — time-to-detection is the measure")

    def test_every_entry_is_dated(self) -> None:
        for row in self.table[1:]:
            with self.subTest(defect=row[1][:40]):
                self.assertRegex(row[0], r"^\d{4}-\d{2}-\d{2}$")

    def test_recurring_classes_are_visible(self) -> None:
        """Not a failure — a report. Three of one class is the finding, not a bug."""
        classes = [row[4].strip().lower() for row in self.table[1:]]
        repeated = {c: classes.count(c) for c in set(classes) if classes.count(c) > 1}
        self.assertTrue(
            all(count >= 2 for count in repeated.values()),
            "sanity: a repeated class must appear at least twice",
        )


class ScriptTests(unittest.TestCase):
    def test_the_script_emits_every_field_it_declares(self) -> None:
        data = quality_baseline.measure()
        missing = [f for f in quality_baseline.ROW_FIELDS if f not in data]
        self.assertEqual(missing, [], f"ROW_FIELDS names fields measure() never sets: {missing}")

    def test_an_unmeasurable_metric_is_none_not_zero(self) -> None:
        """Zero is a reading. Absence must not be reported as a good number."""
        data = quality_baseline.measure()
        for field in ("tests_collected", "transport_boundary_exemptions"):
            value = data[field]
            self.assertTrue(
                value is None or isinstance(value, int),
                f"{field} must be an int or None, never a placeholder",
            )

    def test_transport_imports_are_counted_by_parsing_not_by_grep(self) -> None:
        """Positive control on the one number that is a goal.

        A docstring mentioning the import must not count, or the number this
        codebase is trying to drive down could be moved by editing a comment.
        """
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            mentions = Path(tmp) / "mentions.py"
            mentions.write_text('"""See `import discord` elsewhere."""\nx = "import discord"\n')
            imports = Path(tmp) / "imports.py"
            imports.write_text("import discord\n")
            from_imports = Path(tmp) / "from_imports.py"
            from_imports.write_text("from discord.ext import commands\n")

            self.assertFalse(quality_baseline._imports_transport(mentions))
            self.assertTrue(quality_baseline._imports_transport(imports))
            self.assertTrue(quality_baseline._imports_transport(from_imports))

    def test_the_document_says_which_numbers_are_generated(self) -> None:
        """A reader must be able to tell a generated number from a typed one."""
        text = DOC.read_text(encoding="utf-8")
        self.assertIn("scripts/quality_baseline.py", text)
        self.assertTrue(
            re.search(r"generated", text, re.IGNORECASE),
            "the document must say its structural numbers are generated",
        )


# How far production can move before the series must be updated. Proportional to the
# codebase so it scales, and loose enough that ordinary work does not demand a row —
# 10% of production is a chapter's worth of change, not a commit's.
SERIES_DRIFT_TOLERANCE = 0.10


class TheSeriesMustStayCurrentTests(unittest.TestCase):
    """A measure nobody records is a measure nobody has.

    This is the one thing the rest of this file cannot see. Every other test here
    asks whether the document and the script agree about *what* is measured; none
    asks whether anyone has measured lately. The operator adopted these four measures
    on 2026-08-15 with an explicit caveat — better ones are welcome — and the risk that
    creates is not replacement, which is a decision with a date. It is abandonment,
    which looks exactly like a green suite.
    """

    def setUp(self) -> None:
        self.text = DOC.read_text(encoding="utf-8")
        self.table = _table_with_header(self.text, "date")
        self.headers = [h.strip().lower() for h in self.table[0]]
        self.now = quality_baseline.measure()

    def _last_value(self, metric: str) -> int | None:
        try:
            column = self.headers.index(
                next(h for h in self.headers if _metric_for(h) == metric)
            )
        except (StopIteration, ValueError):
            return None
        for row in reversed(self.table[1:]):
            if column < len(row):
                cell = row[column].strip()
                if cell and cell not in {"—", "-", "n/a"}:
                    try:
                        return int(cell)
                    except ValueError:
                        return None
        return None

    @staticmethod
    def _drift(recorded: int, current: int) -> float:
        return abs(current - recorded) / max(recorded, 1)

    def test_the_last_row_still_describes_this_codebase(self) -> None:
        recorded = self._last_value("production_loc")
        self.assertIsNotNone(recorded, "the series must carry production LOC")
        current = self.now["production_loc"]
        drift = self._drift(recorded, current)
        self.assertLessEqual(
            drift,
            SERIES_DRIFT_TOLERANCE,
            f"production is {current} lines; the last recorded row says {recorded} "
            f"({drift:.0%} drift). The series has stopped describing this codebase, "
            "which makes it a historical document wearing a live one's clothes.\n"
            "  Append the current measurement:\n"
            "      python3 scripts/quality_baseline.py --row",
        )

    def test_the_check_fires_on_a_stale_row(self) -> None:
        """Positive control. An empty result is not evidence of currency."""
        current = self.now["production_loc"]
        stale = int(current * 0.5)
        self.assertGreater(
            self._drift(stale, current),
            SERIES_DRIFT_TOLERANCE,
            "a row recording half the current size must read as stale",
        )

    def test_the_check_tolerates_ordinary_work(self) -> None:
        """Negative control: a guard that fires on every commit gets deleted."""
        current = self.now["production_loc"]
        ordinary = int(current * 0.98)
        self.assertLessEqual(
            self._drift(ordinary, current),
            SERIES_DRIFT_TOLERANCE,
            "a 2% change must not demand a new row",
        )

    def test_the_document_records_that_the_measures_were_adopted(self) -> None:
        """The difference between a proposal and a standard is who owns it.

        `AGENTS.md` tells every future agent that quality is judged here. That was
        written a day before it was true. It is true now, and the provenance belongs
        in the document rather than in a chat log nobody will find.
        """
        self.assertIn("Adopted by the operator", self.text)
        self.assertRegex(
            self.text,
            r"Adopted by the operator \d{4}-\d{2}-\d{2}",
            "an adoption without a date cannot be superseded cleanly",
        )


if __name__ == "__main__":
    unittest.main()
