#!/usr/bin/env bash
# Install this repo's tracked git hooks into .git/hooks.
#
#   ./scripts/install_hooks.sh
#
# Run once per clone, including on the live host. Hooks live in `.git/`, which git
# does not carry, so a tracked source plus an explicit install is the only shape
# that reaches a second machine.
#
# WHY NOT `core.hooksPath` — read before reaching for it:
#
# Pointing `core.hooksPath` at `hooks/` would make this script unnecessary and
# would also **silently disable the pre-commit sanitation guard**, which is
# installed into `.git/hooks/pre-commit` by the operator's practice repo
# (`magic/scripts/configure_workshop_git.sh`) and is deliberately machine-local:
# it needs a private name list this repository does not and should not contain.
# `core.hooksPath` replaces the whole hook directory rather than adding to it, so
# the trade is a slightly nicer install for a repo that stops checking whether
# real people's names are about to be published. Not worth it. If you ever do move
# to `hooksPath`, the sanitation hook has to move with it in the same change.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SRC="$ROOT/hooks"
DEST="$(git rev-parse --git-path hooks)"

if [ -n "$(git config --get core.hooksPath || true)" ]; then
  echo "warning: core.hooksPath is set to '$(git config --get core.hooksPath)'." >&2
  echo "         Hooks installed here may be ignored. See the note in this script." >&2
fi

mkdir -p "$DEST"
installed=0

for src in "$SRC"/*; do
  [ -f "$src" ] || continue
  name="$(basename "$src")"
  target="$DEST/$name"

  if [ -e "$target" ] && ! grep -q "turtleos tracked hook" "$target" 2>/dev/null; then
    if ! diff -q "$src" "$target" >/dev/null 2>&1; then
      # Never clobber a hook this script did not write. The pre-commit sanitation
      # guard is exactly such a hook, and losing it is a publication risk.
      echo "skipping $name — a different hook is already installed there." >&2
      echo "  existing: $target" >&2
      echo "  wanted:   $src" >&2
      echo "  Merge them by hand if both are needed." >&2
      continue
    fi
  fi

  printf '#!/usr/bin/env bash\n# turtleos tracked hook — generated by scripts/install_hooks.sh from hooks/%s\n# Edit the tracked source, then re-run the installer.\nexec "%s" "$@"\n' \
    "$name" "$src" > "$target"
  chmod +x "$target"
  echo "installed $name -> $src"
  installed=$((installed + 1))
done

echo ""
echo "$installed hook(s) installed into $DEST"
echo "Verify the gate actually refuses a red suite before trusting it:"
echo "  ./scripts/install_hooks.sh && echo 'def test_x(): assert False' > tests/test_zz_control.py && \\"
echo "    .git/hooks/pre-push origin HEAD < /dev/null; echo \"exit=\$?\"; rm -f tests/test_zz_control.py"
